---
- name: installation package 
  hosts: VMansible
  tasks:

    - name: install the latest version of apache2
      apt:
        name: apache2
        state: latest

    - name: Install Mysql
      apt:
        name: mariadb-server
        state: present

    - name: Install php
      apt:
        name:
          - php
          - php-mysql
        state: present